### ISSUE TITLE
Error while transferring stakes from cosmos to ethereum

### ISSUE THREAD

**Issue by SudeshGagare** [cosmos/peggy#180]
I[2020-04-13|01:48:20.250] New transaction witnessed                    
I[2020-04-13|01:48:20.250] 
Claim Type: lock
Cosmos Sender: cosmos1waurakxhkg42c628ah5gqfzt6tr7zq826yje8y
Ethereum Recipient: 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
Token Address: 0x409Ba3dd291bb5D48D5B4404F5EFa207441F6CbA
Symbol: stake
Amount: 1
 

Fetching CosmosBridge contract...
Sending new ProphecyClaim to CosmosBridge...
2020/04/13 01:48:20 VM Exception while processing transaction: revert Must be an active validator

**Comment by denalimarsh** [comment]
The relayer signs transactions using the private key from your environment variables. If the account is not an active validator, the contracts will reject the tx.

How to solve:
1. from the root directory copy the example env variables with `cp .env.example .env`
2. replace `ETHEREUM_PRIVATE_KEY` with the private key of an activate validator

Contents of .env.example for reference:
```
# Replace sample private key for an active validator address
# For local testing, use accounts[1] private key from truffle
ETHEREUM_PRIVATE_KEY="ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f"
```

**Comment by SudeshGagare** [comment]
Thanks a lot!!!
Resolved the Issue.
Is there any complete documentation available for peggy ??

**Comment by liu-zhipeng** [comment]
Hi, guys. 
I have met same error on ropsten testnet. 
I have replaced ethereum private key with my account key. 
But it still shows same error. Must be active validator.

How should I fix this? Thanks.
